name: pherii_app
description: A complete Pherii management app in Urdu
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutterflutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  intl: ^0.18.0

dev_dependencies:
 flutter_test: any
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
