name: Build APK

on:
  push:
    branches: [ "main" ]  # main branch میں push ہونے پر run ہوگا

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repository کو checkout کریں
      - uses: actions/checkout@v3

      # Step 2: Flutter setup
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # اپنے Flutter version کے مطابق

      # Step 3: Dependencies install کریں
      - run: flutter pub get

      # Step 4: APK build کریں
      - run: flutter build apk --release

      # Step 5: APK artifact کے طور پر upload کریں (v3)
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
